### ISSUE TITLE
Can you please tag recent releases

### ISSUE THREAD

**Issue by aaronbee** [mbj4668/yang-mode#5]
Hello,

I have installed yang-mode from MELPA Stable, version 0.9.4, and it has an autoload bug that you have since fixed. Would you please tag the recent release so that MELPA Stable picks up the newer code? (I believe a tag is what is required to get MELPA Stable to pick up the code, but I'm not entirely sure.)

Thanks!

**Comment by mbj4668** [comment]
Done!  (sorry for missing this!)
